FROM golang:1.10.3 AS build-env

COPY . /go/src/github.com/openshift/cluster-ingress-operator
WORKDIR /go/src/github.com/openshift/cluster-ingress-operator
RUN go build github.com/openshift/cluster-ingress-operator/cmd/cluster-ingress-operator

FROM scratch
COPY --from=build-env /go/src/github.com/openshift/cluster-ingress-operator/cluster-ingress-operator /bin/cluster-ingress-operator

ENTRYPOINT ["/bin/cluster-ingress-operator"]
