# Load Balancer Service to place in front of the router in cloud environments.
# Ingress Controller specific values are applied at runtime.
kind: Service
apiVersion: v1
metadata:
  # Name is set at runtime.
  namespace: openshift-ingress
  labels:
    app: router
spec:
  type: LoadBalancer
  selector:
    app: router
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
  - name: https
    protocol: TCP
    port: 443
    targetPort: https
