# Cluster role for the operator itself.
# TODO: A lot of these should be replaced by roles in the namespaces for which
# the operator actually needs access.
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openshift-ingress-operator
  annotations:
    capability.openshift.io/name: Ingress
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch

- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - get
  - list
  - update
  - watch

- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - get
  - update

- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - list

- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch

- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - patch
  - watch

- apiGroups:
  - ""
  resources:
  - pods/eviction
  verbs:
  - create

- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list

- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch

- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - create
  - get
  - list
  - update
  - watch

- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - get
  - update

- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - create
  - get
  - update

- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - clusterrolebindings
  - roles
  - rolebindings
  verbs:
  - create
  - get
  - list
  - watch
  - update

- apiGroups:
  - operator.openshift.io
  resources:
  - ingresscontrollers
  verbs:
  - create
  - get
  - list
  - update
  - watch

- apiGroups:
  - operator.openshift.io
  resources:
  - ingresscontrollers/status
  verbs:
  - update

- apiGroups:
  - ingress.operator.openshift.io
  resources:
  - dnsrecords
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch

- apiGroups:
  - ingress.operator.openshift.io
  resources:
  - dnsrecords/status
  verbs:
  - update

- apiGroups:
  - config.openshift.io
  resources:
  - infrastructures
  - ingresses
  - dnses
  - featuregates
  - apiservers
  - networks
  - clusterversions
  - proxies
  verbs:
  - get
  - list
  - watch

- apiGroups:
  - config.openshift.io
  resources:
  - dnses
  - featuregates
  - infrastructures
  - ingresses
  verbs:
  - list
  - watch

- apiGroups:
  - config.openshift.io
  resources:
  - infrastructures/status
  verbs:
  - update

- apiGroups:
  - config.openshift.io
  resources:
  - clusteroperators
  verbs:
  - create
  - get
  - list
  - watch

- apiGroups:
  - config.openshift.io
  resources:
  - clusteroperators/status
  verbs:
  - update

- apiGroups:
  - config.openshift.io
  resources:
  - ingresses/status
  verbs:
  - patch

- apiGroups:
  - networking.k8s.io
  resources:
  - ingressclasses
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch

- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - get
  - list
  - create
  - update
  - watch
  - delete

- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gatewayclasses
  verbs:
  - get
  - list
  - patch
  - watch

- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gateways
  verbs:
  - get
  - list
  - update
  - watch

- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - listenersets
  verbs:
  - get
  - list
  - watch

- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gatewayclasses/status
  - listenersets/status
  verbs:
  - patch

- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gateways/status
  verbs:
  - patch
  - update

- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - get
  - list
  - update
  - watch

- apiGroups:
  - operators.coreos.com
  resources:
  - subscriptions
  verbs:
  - create
  - get
  - list
  - update
  - watch

- apiGroups:
  - operators.coreos.com
  resources:
  - installplans
  verbs:
  - list
  - update
  - watch

- apiGroups:
  - sailoperator.io
  resources:
  - istios
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch

- apiGroups:
  - sailoperator.io
  resources:
  - istiorevisions
  verbs:
  - get
  - list
  - watch

# Mirrored from assets/router/metrics/cluster-role.yaml
- apiGroups:
  - route.openshift.io
  resources:
  - routers/metrics
  verbs:
  - get

# Mirrored from assets/router/cluster-role.yaml
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create

# Mirrored from assets/router/cluster-role.yaml
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create

# Mirrored from assets/router/cluster-role.yaml
# and expanded for the canary-controller.
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch

- apiGroups:
  - route.openshift.io
  resources:
  - routes/custom-host
  verbs:
  - create
  - update

# Mirrored from assets/router/cluster-role.yaml
- apiGroups:
  - route.openshift.io
  resources:
  - routes/status
  verbs:
  - update

# Mirrored from assets/router/cluster-role.yaml
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceNames:
  - hostnetwork
  - restricted

# Mirrored from assets/router/cluster-role.yaml
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - list
  - watch
