# Role for the operator itself.
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ingress-operator
  namespace: openshift-ingress-operator
  annotations:
    capability.openshift.io/name: Ingress
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
rules:
- apiGroups:
  - operator.openshift.io
  resources:
  - ingresscontrollers
  verbs:
  - create
  - get
  - list
  - update
  - watch

- apiGroups:
  - operator.openshift.io
  resources:
  - ingresscontrollers/status
  verbs:
  - update

- apiGroups:
  - ""
  resources:
  - pods
  - services
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch

- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - patch
  - watch

- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
---
# Role for the operator to delete Role and RoleBindings
# in the openshift-config namespace.
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ingress-operator
  namespace: openshift-config
  annotations:
    capability.openshift.io/name: Ingress
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
rules:
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - delete
