# Account for the operator itself. It should require namespace scoped
# permissions.
kind: ServiceAccount
apiVersion: v1
metadata:
  name: ingress-operator
  namespace: openshift-ingress-operator
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
