# Account for the operator itself. It should require namespace scoped
# permissions.
kind: ServiceAccount
apiVersion: v1
metadata:
  name: cluster-ingress-operator
  namespace: openshift-cluster-ingress-operator

---

# Cluster role for the operator itself.
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cluster-ingress-operator
  namespace: openshift-cluster-ingress-operator
rules:
- apiGroups:
  - ingress.openshift.io
  resources:
  - clusteringresses
  verbs:
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - create
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - ""
  - route.openshift.io
  resources:
  - routes
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  - route.openshift.io
  resources:
  - routes/status
  verbs:
  - update
- apiGroups:
  - ""
  - rbac.authorization.k8s.io
  resources:
  - namespaces
  - pods
  - endpoints
  - services
  - serviceaccounts
  - clusterroles
  - clusterrolebindings
  verbs:
  - create
  - list
  - watch

---

# Binds the operator cluster role to its Service Account.
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cluster-ingress-operator
subjects:
- kind: ServiceAccount
  name: cluster-ingress-operator
  namespace: openshift-cluster-ingress-operator
roleRef:
  kind: ClusterRole
  name: cluster-ingress-operator
  namespace: openshift-cluster-ingress-operator
userNames:
- "system:serviceaccount:openshift-cluster-ingress-operator:cluster-ingress-operator"
