contact_links:
- name: File a bug report
  url: https://redhat.atlassian.net/secure/CreateIssueDetails!init.jspa?pid=10325&project=OCPBUGS&issuetype=10016&components=14827
  about: Please use the Red Hat Issue Tracker to report bugs.
- name: Ingress Operator in OpenShift Container Platform
  url: https://docs.redhat.com/en/documentation/openshift_container_platform/latest/html/networking_operators/configuring-ingress
  about: Refer to the OpenShift Container Platform documentation for information about the Ingress Operator in OpenShift Container Platform.
- name: Ingress Operator in OKD
  url: https://docs.okd.io/latest/networking/networking_operators/ingress-operator.html
  about: Refer to the OKD documentation for information about the Ingress Operator in OKD.
