#!/bin/bash

# Extracts downstream OSSM images from a stage catalog (IIB) and generates
# the vendored images.gen.go file with registry.redhat.io image references.
#
# Usage:
#   hack/update-pre-release-sail-images.sh <catalog-image> [ossm-version]
#
# Examples:
#   hack/update-pre-release-sail-images.sh registry-proxy.engineering.redhat.com/rh-osbs/iib:1165135
#   hack/update-pre-release-sail-images.sh registry-proxy.engineering.redhat.com/rh-osbs/iib:1165135 3.4.0

set -euo pipefail

CATALOG_IMAGE="${1:-}"
OSSM_VERSION="${2:-}"

if [[ -z "${CATALOG_IMAGE}" ]]; then
    echo "Usage: hack/update-pre-release-sail-images.sh <catalog-image> [ossm-version]"
    echo ""
    echo "Examples:"
    echo "  hack/update-pre-release-sail-images.sh registry-proxy.engineering.redhat.com/rh-osbs/iib:1165135"
    echo "  hack/update-pre-release-sail-images.sh registry-proxy.engineering.redhat.com/rh-osbs/iib:1165135 3.4.0"
    exit 1
fi

command -v opm >/dev/null 2>&1 || { echo "error: opm is required but not installed"; exit 1; }
command -v jq >/dev/null 2>&1 || { echo "error: jq is required but not installed"; exit 1; }

SCRIPTPATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "${SCRIPTPATH}/.." && pwd)"
TARGET="${ROOT}/vendor/github.com/istio-ecosystem/sail-operator/pkg/install/images.gen.go"

echo "> Rendering catalog ${CATALOG_IMAGE}..."

RENDERED=$(opm render "${CATALOG_IMAGE}" 2>/dev/null)

# Find the target bundle
if [[ -n "${OSSM_VERSION}" ]]; then
    BUNDLE_NAME="servicemeshoperator3.v${OSSM_VERSION}"
else
    BUNDLE_NAME=$(echo "${RENDERED}" | jq -r 'select(.schema == "olm.bundle" and (.name | startswith("servicemeshoperator3.v"))) | .name' | sort -V | tail -1)
    if [[ -z "${BUNDLE_NAME}" || "${BUNDLE_NAME}" == "null" ]]; then
        echo "error: no servicemeshoperator3 bundle found in catalog"
        exit 1
    fi
fi

echo "> Using bundle: ${BUNDLE_NAME}"

# Extract relatedImages for the 4 components we care about
IMAGES=$(echo "${RENDERED}" | jq -r \
    --arg name "${BUNDLE_NAME}" \
    'select(.schema == "olm.bundle" and .name == $name) |
    .relatedImages[] |
    select(.name | test("^images_v[0-9]+_[0-9]+_[0-9]+_(istiod|proxy|cni|ztunnel)$")) |
    "\(.name) \(.image)"')

if [[ -z "${IMAGES}" ]]; then
    echo "error: no matching relatedImages found in bundle ${BUNDLE_NAME}"
    exit 1
fi

# Parse images into an associative array keyed by version
declare -A ISTIOD PROXY CNI ZTUNNEL
declare -a VERSIONS_SEEN

while read -r name image; do
    # images_v1_30_1_istiod -> v1_30_1 istiod
    stripped="${name#images_}"
    if [[ "${stripped}" =~ ^(v[0-9]+_[0-9]+_[0-9]+)_(.+)$ ]]; then
        version_raw="${BASH_REMATCH[1]}"
        component="${BASH_REMATCH[2]}"
        # v1_30_1 -> v1.30.1
        version="${version_raw//_/.}"

        case "${component}" in
            istiod)  ISTIOD["${version}"]="${image}" ;;
            proxy)   PROXY["${version}"]="${image}" ;;
            cni)     CNI["${version}"]="${image}" ;;
            ztunnel) ZTUNNEL["${version}"]="${image}" ;;
        esac

        # Track unique versions in order
        if [[ -z "${ISTIOD["${version}"]:-}${PROXY["${version}"]:-}${CNI["${version}"]:-}${ZTUNNEL["${version}"]:-}" ]] 2>/dev/null || ! printf '%s\n' "${VERSIONS_SEEN[@]}" | grep -qx "${version}" 2>/dev/null; then
            VERSIONS_SEEN+=("${version}")
        fi
    else
        echo "warning: could not parse relatedImage name: ${name}"
    fi
done <<< "${IMAGES}"

# Deduplicate and sort versions
VERSIONS=($(printf '%s\n' "${VERSIONS_SEEN[@]}" | sort -uV -r))

echo "> Found ${#VERSIONS[@]} versions: ${VERSIONS[*]}"

# Generate images.gen.go
cat > "${TARGET}" << 'HEADER'
// Copyright Istio Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by hack/update-pre-release-sail-images.sh. DO NOT EDIT.

package install

import "github.com/istio-ecosystem/sail-operator/pkg/config"

func init() {
	config.Config.ImageDigests = map[string]config.IstioImageConfig{
HEADER

for version in "${VERSIONS[@]}"; do
    istiod="${ISTIOD["${version}"]:-}"
    proxy="${PROXY["${version}"]:-}"
    cni="${CNI["${version}"]:-}"
    ztunnel="${ZTUNNEL["${version}"]:-}"

    cat >> "${TARGET}" << ENTRY
		"${version}": {
			IstiodImage:  "${istiod}",
			ProxyImage:   "${proxy}",
			CNIImage:     "${cni}",
			ZTunnelImage: "${ztunnel}",
		},
ENTRY
done

cat >> "${TARGET}" << 'FOOTER'
	}
}
FOOTER

echo "> Generated ${TARGET}"
echo ""
echo "Verify with:"
echo "  go build ./..."
echo "  go test ./pkg/operator/controller/gatewayclass/ -run TestSailLibraryImageDigestsAreDownstream"
