# Account for the operator itself. It should require namespace scoped
# permissions.
kind: ServiceAccount
apiVersion: v1
metadata:
  name: cluster-ingress-operator
  namespace: openshift-cluster-ingress-operator

---

# Role for the operator itself.
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cluster-ingress-operator
  namespace: openshift-cluster-ingress-operator
rules:
- apiGroups:
  - ingress.openshift.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"

---

# Binds the operator role to its Service Account.
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cluster-ingress-operator:cluster-ingress-operator
subjects:
- kind: ServiceAccount
  name: cluster-ingress-operator
  namespace: openshift-cluster-ingress-operator
roleRef:
  kind: Role
  name: cluster-ingress-operator
  apiGroup: rbac.authorization.k8s.io
