// Code generated by hack/override-ossm-images.sh. DO NOT EDIT.
// Overrides vendored upstream images with downstream registry.stage.redhat.io references.
// Delete this file to use the vendored images from the sail library instead.

package gatewayclass

import "github.com/istio-ecosystem/sail-operator/pkg/config"

func init() {
	config.Config.ImageDigests = map[string]config.IstioImageConfig{
		"v1.30.4": {
			IstiodImage:  "registry.stage.redhat.io/openshift-service-mesh/istio-pilot-rhel9@sha256:f97057b85ffe2c06774f82a3985738dd87ee4ed6bc003933923449296e2a0513",
			ProxyImage:   "registry.stage.redhat.io/openshift-service-mesh/istio-proxyv2-rhel9@sha256:de0ddfa8be68efb0a8015bc079490ceb1fc9c437ef548345755b09609281c38e",
			CNIImage:     "registry.stage.redhat.io/openshift-service-mesh/istio-cni-rhel9@sha256:dc1d4cae4b5c9123b29ed22d6c1abacfed11a5ca9ab968adee71403c3b8a021c",
			ZTunnelImage: "registry.stage.redhat.io/openshift-service-mesh/istio-ztunnel-rhel9@sha256:e1d2d1c3153178e43796fe0dfce3f3b0816cd5c95cf1dcea1aa21f1f5cf8a966",
		},
		"v1.30.3": {
			IstiodImage:  "registry.stage.redhat.io/openshift-service-mesh/istio-pilot-rhel9@sha256:6a4f5a2ffa5fc9aa687bb812c9b427dc61fc109b846cdf7d70eef28c5fe08faa",
			ProxyImage:   "registry.stage.redhat.io/openshift-service-mesh/istio-proxyv2-rhel9@sha256:e8842597aaa261b91be69ffc6501848958de95b714bb7782544d8a923eee619a",
			CNIImage:     "registry.stage.redhat.io/openshift-service-mesh/istio-cni-rhel9@sha256:80656e6f4d680953d568791338083cb2bef32c443f5f74f227d4e0738be27b4b",
			ZTunnelImage: "registry.stage.redhat.io/openshift-service-mesh/istio-ztunnel-rhel9@sha256:cfd72e7c8400aa984c0872c63edf8dce83391bc579360ef48d98958a5e45faa7",
		},
		"v1.30.1": {
			IstiodImage:  "registry.stage.redhat.io/openshift-service-mesh/istio-pilot-rhel9@sha256:38b1561e4c2d9da341ae4fe809de6a3decabdc861583e52e4a6b85f608682a7f",
			ProxyImage:   "registry.stage.redhat.io/openshift-service-mesh/istio-proxyv2-rhel9@sha256:d770608385272197ccf83efa9d1b7b52a01828aa644d875794f025b9d45af381",
			CNIImage:     "registry.stage.redhat.io/openshift-service-mesh/istio-cni-rhel9@sha256:e27a86751f51b3836c9638b719e14e3f4444ff360e6c3add6be24ee4a1cd436b",
			ZTunnelImage: "registry.stage.redhat.io/openshift-service-mesh/istio-ztunnel-rhel9@sha256:194fe2d15251e53544eae4fa5124ec2de2a8bf70646115bb2f9c30b615ff5df5",
		},
		"v1.28.10": {
			IstiodImage:  "registry.stage.redhat.io/openshift-service-mesh/istio-pilot-rhel9@sha256:d5adf3101d4e14c710cd05afb3fa53498e3c5fb31a120f1bb007fba2e3b376f8",
			ProxyImage:   "registry.stage.redhat.io/openshift-service-mesh/istio-proxyv2-rhel9@sha256:1fc05d17a76d31503f68c5bde3057750a2c575981535756112c06589f88c8c55",
			CNIImage:     "registry.stage.redhat.io/openshift-service-mesh/istio-cni-rhel9@sha256:b0326842b92537e57fa887193ef604b1904ae14d047b50f897d3f35eb3f18698",
			ZTunnelImage: "registry.stage.redhat.io/openshift-service-mesh/istio-ztunnel-rhel9@sha256:b3a5a31f8f23a4dd1144805c4763b6e7bed0912214fe413f96bc66436b29ae68",
		},
		"v1.28.8": {
			IstiodImage:  "registry.stage.redhat.io/openshift-service-mesh/istio-pilot-rhel9@sha256:034b83f99536433ea79a119c73473be8962b3317c8c259ace1ffeb74bbc0cf06",
			ProxyImage:   "registry.stage.redhat.io/openshift-service-mesh/istio-proxyv2-rhel9@sha256:e1c587919c651e10658506ba86637c08e9e2984aae797ab78364dfc2c7e0e0cb",
			CNIImage:     "registry.stage.redhat.io/openshift-service-mesh/istio-cni-rhel9@sha256:f5036871f4f1badcba63053bb4e92dfeac7e7d2b4638254671a5ac5a88c95068",
			ZTunnelImage: "registry.stage.redhat.io/openshift-service-mesh/istio-ztunnel-rhel9@sha256:dfe3db9c8ca90597d54a21afb090ecfa00353efb110efefcea53fc986ff3c425",
		},
		"v1.28.6": {
			IstiodImage:  "registry.stage.redhat.io/openshift-service-mesh/istio-pilot-rhel9@sha256:4191e8f0fb1ce2b8125991793d09b9b1c404822a6ef2121e99aee8a007cd1011",
			ProxyImage:   "registry.stage.redhat.io/openshift-service-mesh/istio-proxyv2-rhel9@sha256:145c3cdaccfd5dd89cbeee2f7150653f1e157ef722c5573f74194027ed8460c9",
			CNIImage:     "registry.stage.redhat.io/openshift-service-mesh/istio-cni-rhel9@sha256:c3665461b78a9ea36175fd75fba29d704718c2a3ef28d59ba87923b53e25c86a",
			ZTunnelImage: "registry.stage.redhat.io/openshift-service-mesh/istio-ztunnel-rhel9@sha256:12af9e7c781ebffafaf4b753fcfd8a77c3193813ba7b8a6e8b414153274f4fff",
		},
		"v1.28.5": {
			IstiodImage:  "registry.stage.redhat.io/openshift-service-mesh/istio-pilot-rhel9@sha256:1866b2e055c40e28fdc627f66c2cddbc0fda8aae41f3ad9ae98b92b49cd2cd57",
			ProxyImage:   "registry.stage.redhat.io/openshift-service-mesh/istio-proxyv2-rhel9@sha256:63b4b95a3c106d30df9bffca17a0657d59cc5b27980fd56f82ec3ad97cb22f31",
			CNIImage:     "registry.stage.redhat.io/openshift-service-mesh/istio-cni-rhel9@sha256:d44c702db3fc41bed08b28044d5527300a5933eb62552f8f6b7fc977456dfd09",
			ZTunnelImage: "registry.stage.redhat.io/openshift-service-mesh/istio-ztunnel-rhel9@sha256:0242201d020be7922c25a728b60816b220d461dd788a2c493425f105b12dc27d",
		},
		"v1.28.4": {
			IstiodImage:  "registry.stage.redhat.io/openshift-service-mesh/istio-pilot-rhel9@sha256:978f840ceda7eb00c6f15740bcd60e241bee732cd215e9de464ce431b0156ffa",
			ProxyImage:   "registry.stage.redhat.io/openshift-service-mesh/istio-proxyv2-rhel9@sha256:ba78d718627a0662f61ec633fdd2867ba5c24be6bdbc6df672d46456fb399dba",
			CNIImage:     "registry.stage.redhat.io/openshift-service-mesh/istio-cni-rhel9@sha256:f8abbd0d6c7758cf2ccd49dba34921e3ac9b6e4cdbfed4e5fb38dc9a11d30a5d",
			ZTunnelImage: "registry.stage.redhat.io/openshift-service-mesh/istio-ztunnel-rhel9@sha256:2d5a3154e7b6b8d7eadb851a86cc5b7ee556b923843e73ae56197e875c564b03",
		},
		"v1.27.9": {
			IstiodImage:  "registry.stage.redhat.io/openshift-service-mesh/istio-pilot-rhel9@sha256:8e98ca24cc00ccfcfdc66277e6e96aa5c8b77bd0561c1cbdbf5856871fa6908b",
			ProxyImage:   "registry.stage.redhat.io/openshift-service-mesh/istio-proxyv2-rhel9@sha256:e5262c8626da775e0e20118dce7c8ddfc339a1b9a46de80a4684fdeafc95a365",
			CNIImage:     "registry.stage.redhat.io/openshift-service-mesh/istio-cni-rhel9@sha256:07db66f390e3fcb18b9b87b8aea4b35d6809fd0959e3995226c7dd22ece27819",
			ZTunnelImage: "registry.stage.redhat.io/openshift-service-mesh/istio-ztunnel-rhel9@sha256:ab67b6a58a7cc272f8d32ee86e402eb7f8031588a71fb62ea3778572393e07ae",
		},
		"v1.27.8": {
			IstiodImage:  "registry.stage.redhat.io/openshift-service-mesh/istio-pilot-rhel9@sha256:2ae8fa9bc0412dacd57f40f293caa09d68ff19eb63a99bc8d5dc1f96db9413c2",
			ProxyImage:   "registry.stage.redhat.io/openshift-service-mesh/istio-proxyv2-rhel9@sha256:234d58ad8033644a72f769ace359a5232c52a2532e851bd374334b3c4cf1d4d8",
			CNIImage:     "registry.stage.redhat.io/openshift-service-mesh/istio-cni-rhel9@sha256:a5934a176e87c452b98d7006bc5e0709b22d80b478bd9b9f13f23ffc612552d9",
			ZTunnelImage: "registry.stage.redhat.io/openshift-service-mesh/istio-ztunnel-rhel9@sha256:cb6adbadc22ca80888f06094c82a402a43526d8a3081e47e6332bcf5355729db",
		},
		"v1.27.5": {
			IstiodImage:  "registry.stage.redhat.io/openshift-service-mesh/istio-pilot-rhel9@sha256:2e515a40de141bd4e516bfcf4fd0cbb8d236ac02799a7a35d77ae44f53916bc9",
			ProxyImage:   "registry.stage.redhat.io/openshift-service-mesh/istio-proxyv2-rhel9@sha256:650da1e2ad1cb93e6a0231dba7ca1f27f4cccac84e5925135281adc629a0caea",
			CNIImage:     "registry.stage.redhat.io/openshift-service-mesh/istio-cni-rhel9@sha256:2929b7df3da8228a728945542647ec5450c0585a2ed5cbdb84f8e3d81ab41806",
			ZTunnelImage: "registry.stage.redhat.io/openshift-service-mesh/istio-ztunnel-rhel9@sha256:0ae2919cd446e0e1f0a21d0850e7809ba8f44c06d484c023b3bee2787ca4bdd0",
		},
		"v1.27.3": {
			IstiodImage:  "registry.stage.redhat.io/openshift-service-mesh/istio-pilot-rhel9@sha256:0850242436e88f7d82f0f2126de064c7e0f09844f31d8ff0f53dc8d3908075d9",
			ProxyImage:   "registry.stage.redhat.io/openshift-service-mesh/istio-proxyv2-rhel9@sha256:7d15cebf9b62f3f235c0eab5158ac8ff2fda86a1d193490dc94c301402c99da8",
			CNIImage:     "registry.stage.redhat.io/openshift-service-mesh/istio-cni-rhel9@sha256:ddadd677161ad8c1077dd156821d6b4e32742ccbb210e9c14696fa66a58c0867",
			ZTunnelImage: "registry.stage.redhat.io/openshift-service-mesh/istio-ztunnel-rhel9@sha256:b2b3216a05f6136ed9ddb71d72d493030c6d6b431682dddffa692c760b6c9ba1",
		},
	}
}
